name: Experimental Workflows
on: workflow_dispatch
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
          echo "$SSH_FINGERPRINT" > ~/.ssh/known_hosts
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_FINGERPRINT: ${{secrets.SSH_FINGERPRINT}}
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: Copy stuff
        run: |
          ls ~/
          ls ${{ github.workspace }}
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}  'rm -rf /home/msauth/test'
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}  'ls /home/msauth'
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}  'mkdir -p /home/msauth/test'
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}  'ls /home/msauth'
          #scp -r ${{ github.workspace }}/test.md ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/test/test.md