name: Experimental Workflows
on: workflow_dispatch
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
          echo "$SSH_FINGERPRINT" > ~/.ssh/known_hosts
          ls ~/.ssh
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_FINGERPRINT: ${{secrets.SSH_FINGERPRINT}}
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: Copy stuff
        run: |
          ssh staging  'rm -rf /home/msauth/test'
          ssh staging  'ls /home/msauth'
          ssh staging  'mkdir -p /home/msauth/test'
          ssh staging  'ls /home/msauth'
          ls /home/runner/work
          ls /home/runner/work/github_actions_1
          ls /home/runner/work/github_actions_1/github_actions_1
          cat ${{ github.workspace }}/test.md
          scp -r ${{ github.workspace }}/test.md staging:~/test/test.md