# Step 1
name: Deploy Go Program

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - run: |
        echo "A initial message"
        ls
        mkdir -p ~/.ssh
        ssh-keyscan auth.thinkovation.com > ~/.ssh/known_hosts
        ls ~/.ssh
        echo "Another message or command"
        #python myscript.py
        #bash some-shell-script-file.sh -xe
    - run: echo "One last message"
     
