# Step 1 V4
name: Deploy Go Program

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Copy assets and binary to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        fingerprint: ${{ secrets.SSH_FINGERPRINT }}
        script: |
          # Remove existing binary and assets folder
          ls ~/
          rm -rf ~/test
          mkdir -p ~/test
          ls ~/test/
          touch ~/test/foo.md
          scp -r test.md ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/test
          ls ~/test/
    
     
